engine/internal/modelsyncer/syncer.go
engine/internal/modelsyncer/syncer_test.go

We have changed the original model ID format.

Remove the model name conversion for Ollama

---

README.md
build/engine/Dockerfile
configs/engine/config.yaml
deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/cmd/run.go
engine/internal/config/config.go
engine/internal/ollama/manager.go

For some reason, pulling image at Dockerfile stopped working.
I couldn't figure it why, and decided to just pull images at startup time.

Make Ollama pull images at startup time

---

deployments/engine/templates/deployment.yaml

Fix the following error:
- error calling gt: incompatible types for comparison

Fix helm chart

---

engine/internal/ollama/manager.go

Ollama uses different templates and parameters for each model.

Change Ollma modelfile based on models

---

deployments/server/templates/service.yaml

Remove a server for gRPC

---

deployments/server/templates/service.yaml
deployments/server/values.yaml

Use this to set timeout related kong parameters

Be able to specify service annotations

---

deployments/server/templates/rbac.yaml

Use "" for the apiGroups instead of "*".

Make a minor change to the Role definition

---

pkg/k8s/informer.go

Some helper functions are not giving much value, and just merging these functions would improve readability.

Merge functions in pkg/k8s/informer.go

---

server/internal/router/router.go

This is a personal preference, but let me make the change.

Call findLeastLoadedEngine from GetEngineForModel

---

server/internal/router/route_map.go
server/internal/router/router.go

- Log on listModels seems to be too verbose
- Add "Dumping.." in printRoute().

Make a minor fix to logging

---

engine/cmd/run.go
engine/internal/modelsyncer/syncer.go
engine/internal/modelsyncer/syncer_test.go
engine/internal/server/server.go

Also apply the name conversion for Ollama.

Update syncer's cache when deleting a model

---

deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/cmd/run.go
engine/internal/config/config.go

modelManagerWorkerServiceServerAddr
-> modelManagerServerWorkerServiceAddr

Make a minor rename to config field name

---

deployments/server/templates/configmap.yaml
deployments/server/values.yaml

Enable authorization in inference-server

---

server/cmd/run.go
server/internal/infprocessor/infprocessor.go
server/internal/infprocessor/infprocessor_test.go
server/internal/server/completions.go
server/internal/server/completions_test.go
server/internal/server/server.go

No functional change, but introduce a queue when processing chat completion requests.
This is for up-coming change to support multi-cluster environment.

Introduce queue abstraction

---

common/pkg/sse/const.go
common/pkg/sse/scanner.go
common/pkg/sse/scanner_test.go
server/internal/server/completions.go
server/internal/server/completions_test.go

To use it from engine as well.

Move the logic for scanning SSE to the common package

---

engine/internal/modelsyncer/syncer.go
engine/internal/server/server.go

The function is already called from processor. Do not call again as Kong (?) rejects a request with multiple authorization contexts.

Do not call auth.AppendWorkerAuthorization more than once

---

engine/internal/processor/processor.go
server/internal/server/completions.go

Started getting 400 when these are set.

Clear toolchoice and tools

---

server/internal/infprocessor/infprocessor.go
server/internal/server/completions.go

This reverts commit fc38d2e0422184873c53832b989470b60e258a00.

Revert "Increase the channel size as a quick hack (#168)"

---

server/internal/infprocessor/infprocessor.go
server/internal/infprocessor/infprocessor_test.go

When the context is canceled from WaitForCompletion, we no longer read from the channels of the task, but the processor still attempts to write when it receives a message from the engine.
We need to spawn a gorountine to read messages whenever comes. We could also increase the channel buffer to 1 (and keep sufficient buffer for resp.Body), but just reading from channels seems simpler.

Avoid a deadlock when a context is cannceled

---

deployments/engine/templates/deployment.yaml
deployments/engine/templates/service.yaml

This reverts commit 93e01c45db83149eb54c1fc40f87aaf05fd28fb7.
Add back service.

Revert "Remove the service from engine"

---

api/v1/inference_server.pb.go
api/v1/inference_server.proto
api/v1/inference_server_worker.swagger.json
buf.lock

This is mainly for upcoming legacy completion support, but the CLI can also use this.

Define ChatCompletionChunk

---

deployments/engine/templates/pvc.yaml
deployments/engine/values.yaml

Also increase the default PVC size.

Make a minor fix to PVC Helm: storageClass -> storageClassName

---

deployments/engine/templates/deployment.yaml
deployments/engine/values.yaml

Consolidate the resource defininition. The GPU allocation now needs to be part of the resource definion.

Fix the nvidia GPU resource definition (backward incompat change)

---

server/internal/infprocessor/infprocessor.go
server/internal/server/completions.go
server/internal/server/legacy_completions.go

Also avoid too frequent Flush as it seems it can make things slower.

Fix a bug in the legacy completion implemtation

---

deployments/engine/values.yaml
deployments/server/values.yaml

The chagne was made to the server by mistake.

Correctly update engine default resourecs

---

deployments/engine/values.yaml

Setting this to true didn't help.

Set forceSpreading to false

---

deployments/engine/templates/scaledobject.yaml

Remove the scaling on server metrics

---

deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/internal/config/config.go
engine/internal/ollama/env.go

This controls the maxiumum number of requests.

Be able to configure Ollama numParallel

---

engine/cmd/pull.go
engine/cmd/run.go
engine/internal/manager/manager.go
engine/internal/modelsyncer/syncer.go
engine/internal/modelsyncer/syncer_test.go
engine/internal/ollama/manager.go
engine/internal/vllm/manager.go

We currently don't use this. Also vLLM doesn't support it.

Remove DeleteModel from Manager

---

engine/internal/runtime/client.go
engine/internal/runtime/ollama_client.go

Move the code that we can share with vLLM from OllamaClient to commonClient.

Define GetAddress and deploymentRuntime in commonClient

---

deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/cmd/alpha.go
engine/cmd/pull.go
engine/internal/config/config.go
engine/internal/modelsyncer/syncer.go
engine/internal/runtime/client.go
engine/internal/runtime/ollama_client.go
engine/internal/runtime/vllm_client.go

No actual implementation of pulling logic and VLLMClient, but this commit makes surrounding change.

Add initial stub for vLLM support

---

engine/cmd/run.go
engine/internal/ollama/payload.go

To fix exising deployments. We can remove once all are fixed.

Delete orphaned runner dir

---

deployments/engine/templates/serviceaccount.yaml
deployments/engine/values.yaml

This is required to use an existing service account.

Add back serviceAccount.create

---

deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/internal/config/config.go
engine/internal/runtime/client.go

This will be useful until we support autoscaling.

Be able to specify the number of replicas of a runtime

---

deployments/engine/templates/deployment.yaml

Remove HF_TOKEN env

---

engine/internal/runtime/vllm_client.go
engine/internal/vllm/models.go

This is one of the changes required to support AWQ.
We need to change model-manager and modelsyncher to make this work.

Support the AWQ quantization in vLLM execution

---

engine/cmd/alpha.go

The bug was added by my change.

Fix a bug where incorrect gRPC connection is used

---

deployments/engine/values.yaml

https://blog.vllm.ai/2024/09/05/perf-update.html

Bump vLLM to 0.6.0

---

engine/internal/runtime/vllm_client.go

The plan is to delete the vllm package. This doesn't have much specific logic for vLLM currently, and we can repurpose the code to a generic model download functionality.

Move helper functions from vllm/models.go to runtime/vllm_client.go

---

engine/internal/vllm/models.go

Forgot in https://github.com/llm-operator/inference-manager/pull/314/files

Delete functions from vllm/models.go

---

engine/cmd/pull.go
engine/cmd/run.go
engine/internal/modeldownloader/modeldownloader.go
engine/internal/models/models.go
engine/internal/models/models_test.go
engine/internal/modelsyncer/syncer.go
engine/internal/modelsyncer/syncer_test.go
engine/internal/processor/processor.go
engine/internal/runtime/client.go
engine/internal/runtime/client_test.go
engine/internal/runtime/ollama_client.go

Still supported only in Ollama.

Support fine-tuning models in the new architecture

---

engine/cmd/run.go
engine/internal/runtime/client.go
engine/internal/runtime/manager.go
engine/internal/runtime/manager_test.go

No functional change, but this is for an up-coming change that supports different runtimes for models.

Introduce ClientFactory

---

engine/internal/config/config.go

The previous commit added a bogus check.

Remove a bug in the runtime config change

---

go.mod
go.sum
server/internal/server/completions.go

Avoid using user ID as it can contain PIIs.

Track internal user ID instead in usages

---

engine/cmd/run.go
engine/internal/runtime/preloader.go

When LLMariner is initially deployed, a model specified in the preload list might not be yet available. Avoid crash in such a case as it can confuse end users.

Do not crash when a model is being loaded

---

engine/internal/runtime/triton_client.go

8001 is used by triton gRPC service

Use port 9000 for triton proxy

---

engine/internal/runtime/vllm_client.go

This conversion is currently needed.

Remove "ft:" prefix when passing model IDs to the vLLM runtime

---

server/internal/infprocessor/infprocessor.go

fix(server): fix a bug in AddOrUpdateEngineStatus

---

server/internal/infprocessor/infprocessor.go

For upcoming change. I'm planning to add a logic that forwards a TaskResult to another server.
The forwarding logic needs to know if the task completes without extra processing.

chore(server): factor out isTaskCompleted

---

server/internal/infprocessor/infprocessor.go
server/internal/infprocessor/infprocessor_test.go
server/internal/server/ws_server.go

This is for upcoming change where we register an engine without cluster info.

refactor(server): remove the use of clusterInfo from infprocessor

---

server/internal/infprocessor/infprocessor.go

We didn't need to include the function in the interface.
Also rename the interface.

refactor(server): drop Recv from engineCommunicator

---

server/internal/infprocessor/infprocessor.go
server/internal/infprocessor/infprocessor_test.go

The function returns all engines. Used by upcoming change.

feat(server): add Engines() to infprocessor.P

---

deployments/engine/templates/configmap.yaml
deployments/engine/values.yaml
engine/internal/config/config.go
engine/internal/config/model_config.go
engine/internal/config/model_config_test.go
engine/internal/runtime/client.go
engine/internal/runtime/vllm_client_test.go

Also fix a bug on the runtime annotation.

feat(engine): remove legacy runtime config

---

engine/cmd/run.go
engine/internal/processor/processor.go
engine/internal/runtime/client.go
engine/internal/runtime/manager.go
engine/internal/runtime/manager_test.go

Fix leader-election settings and event handling for runtime deletion to handle request correctly with multiple replicas.

fix(engine): fix leader-election and runtime deletion handling

---

server/internal/integrationtest/integration_test.go

Here is an example failure:
https://github.com/llmariner/inference-manager/actions/runs/11861683469/attempts/3?pr=493
panic: Log in goroutine after TestIntegration has completed: worker: "level"=0 "msg"="Unregistered engine" "engineID"="e1"
The issue was that the engine removal was in-progress when the test ended. This commit changes the test to wait until all engines are removed.

test(server): fix the flaky integration test

---

engine/internal/runtime/client.go

Using these annotations for Prometheus metrics scraping

feat(runtime): set runtime/model annotations to the pod template

---

engine/cmd/run.go
engine/internal/autoscaler/autoscaler.go

This is for the upcoming keda scaler.

refactor(engine): rename Multiautoscaler to BuiltinScaler

---

engine/internal/runtime/preloader.go

Ignore ErrRequestCanceled as it returns when a pod is unschedulable. Returning an error from here will make the preloading fails, but an unschedulable pod is expected when a cluster is being autoscaled.

fix(engine): ignore ErrRequestCanceled from Preloader.pullModel

---

engine/internal/runtime/model_format.go

chore improve the error message on missing GGUF file

---

server/internal/server/completions.go

Do not clear Tools if there is a non-RAG tool defined.

fix: support non-RAG tools

---

go.mod
server/internal/server/completions.go
server/internal/server/completions_test.go

fix: fix a bug in handleToolsForRAG

---

server/internal/server/status.go
server/internal/server/status_test.go

Sum up in-flight requests from all engines.

fix: fix the calculation of per-cluster in-flight request

---

engine/cmd/pull.go
engine/internal/modeldownloader/modeldownloader.go
engine/internal/runtime/model_format.go
engine/internal/runtime/ollama_client.go
go.mod
go.sum

issue: https://github.com/llmariner/llmariner/issues/627

feat: support ollama format model

---

engine/internal/processor/processor.go
engine/internal/processor/processor_test.go
engine/internal/runtime/client.go
engine/internal/runtime/manager.go
engine/internal/runtime/manager_test.go
engine/internal/runtime/ollama_manager.go

Still yet support Ollama dynamic loading.

feat(engine): support model deactivation

---

engine/internal/processor/processor.go
server/internal/taskexchanger/task_receiver.go
server/internal/taskexchanger/task_receiver_test.go

feat(server,engine): send engine status more frequently

---

server/cmd/run.go

We noticed that engines will reconnect to the same server again.

fix: add delay before sending goaway tasks

---

server/internal/taskexchanger/task_receiver.go

We see a case where server doesn't recreate a task receiver after the other server deletes the sender after RPC cancelation.

fix: tweak the error handling in task receiver

---

engine/internal/runtime/ollama_manager.go
engine/internal/runtime/ollama_manager_test.go

Do not access waitCh outside of the lock.
Change the model to have a slice of channels.

fix: fix the handling of waitCh

---

server/internal/infprocessor/infprocessor.go
server/internal/infprocessor/task.go

scheduleTask is not in the original context, so calling ctx.Deadline() there didn't work.

fix: set the task timeout correctly

---

engine/internal/processor/processor.go
engine/internal/processor/processor_test.go

Transiently manage two connections.

feat: connect to a server immediately when a go-away task is received

---

engine/internal/modeldownloader/huggingface/download.go
engine/internal/modeldownloader/huggingface/download_test.go

- added_tokens.json
- merges.txt
- normalizer.json

fix: add more optional file download

---

hack/helm-apply-deps.sh

The YAML file was renamed to helmfile.yaml.gotmpl.

fix: fix hack/helm-apply-deps.sh

---

engine/internal/runtime/ollama_manager.go

This is required as DeployRuntime now makes an API call to Model Manager Server.

fix: append auth in OllamaManager

---

engine/cmd/run.go
engine/internal/runtime/client.go
engine/internal/runtime/manager.go
engine/internal/runtime/manager_test.go
engine/internal/runtime/model_cache_test.go
engine/internal/runtime/nim_client.go
engine/internal/runtime/ollama_client.go
engine/internal/runtime/ollama_manager.go
engine/internal/runtime/triton_client.go
engine/internal/runtime/updater.go
engine/internal/runtime/vllm_client.go
engine/internal/runtime/vllm_client_test.go

chore: make DeployRuntime take a Model proto

---

engine/internal/runtime/manager.go
engine/internal/runtime/manager_test.go
engine/internal/runtime/ollama_manager.go
engine/internal/runtime/ollama_manager_test.go
engine/internal/runtime/runtime.go

This reverts commit 3bca74b90f8fcba389d692f0e163ab736bd988ce.

Revert "chore: add the 'model' field to 'runtime' for upcoming changes (#1027)"

---

engine/internal/runtime/client.go
engine/internal/runtime/triton_client.go

This allows us to get an error detail from a pod status.

feat: set TerminationMessagePolicy

---

deployments/engine/templates/role.yaml
engine/internal/runtime/pod_monitor.go
engine/internal/runtime/pod_monitor_test.go

Stop getting the information with the log API call.

feat: extract pod error message from terminated status
