llmariner/inference-manager

- deployments/engine/values.yaml
To reduce the number of values that a user needs to specify.
> Set default values for the service addr

- go.mod
- go.sum
- server/cmd/run.go
- server/internal/config/config.go
- server/internal/server/completions.go
- server/internal/server/ollama_client.go
- server/internal/server/server.go
Ollama go sdk does not support chat using OpenAI compatible API, which is recently introduced in Ollama. Copy related functions from Ollama SDK and alternate it to process interfence-manager-server messages
> Make ollama_client using Ollama OpenAI compatible API

- deployments/engine/templates/deployment.yaml
- deployments/engine/templates/scaledobject.yaml
- deployments/engine/values.yaml
- Do not set env var for NVIDIA drivers. This is done by the container runtime.
- Disable KEDA by default. We can enable once we update the overall installation flow.
- Make other minor tweaks
> Make small changes to Helm charts

- configs/server/config.yaml
- docker-compose.yaml
This is convenient to test inference-manager-{engine,server} locally without a kind cluster, which requires docker-image loading.
> Add docker-compose.yaml

- server/internal/router/router.go
Let me make a minor change. refreshRoutes does that.
> Remove unneeded call of printRoute

- server/internal/k8s/informer.go
- server/internal/router/router.go
We don't need to print before/after Start().
Also rename Start() to Run() and move the goroutine to the caller. This is a personal preference.
> Remove redudant log message on informer

- server/internal/server/completions.go
- server/internal/server/server.go
This is necessary to mock/fake router in a unit test.
> Define the engineGetter interface

- engine/internal/modelsyncer/syncer.go
- engine/internal/modelsyncer/syncer_test.go
This was to be consistent with OpenAI, but it is making things complicated unnecessarily.
> Remove the logic for removing "ft:" from model name

- common/pkg/models/ollama.go
- common/pkg/models/ollama_test.go
- engine/internal/modelsyncer/syncer.go
- engine/internal/modelsyncer/syncer_test.go
- server/internal/server/completions.go
Ollama doesn't accept "ft:" prefix as a model name cannot contain more than ":".
Drop the "ft:" prefix and have the same logic in the inference-manager-server.
> Remove "ft:" only from Ollama model names

- engine/internal/modelsyncer/syncer.go
- engine/internal/ollama/manager.go
- engine/internal/server/server.go
Query model names from Syncer instead of Ollama as Ollama can return a different model name (e.g., ":latest" suffix, "ft:" prefix).
> engine: Make ListModels return model names without Ollama conversion

- engine/cmd/run.go
- engine/internal/ollama/manager.go
Ollama processes env vars from init(), and setting the env var later in the code doesn't work.
https://github.com/ollama/ollama/blob/main/envconfig/config.go#L130
> Do not initialize Ollama client from env var

- api/v1/inference_server_worker.pb.go
- api/v1/inference_server_worker.proto
- api/v1/inference_server_worker.swagger.json
- api/v1/inference_server_worker_grpc.pb.go
- engine/cmd/run.go
- engine/internal/processor/processor.go
- server/cmd/run.go
- server/internal/infprocessor/infprocessor.go
- server/internal/server/ws_server.go
Engine makes a bi-directional gRPC call to server and register itself.
Later we will add a logic to fetch inference tasks via the same streaming RPC call.
> Make engine register via gRPC call

- server/internal/infprocessor/pipe.go
- server/internal/infprocessor/pipe_test.go
This is used to write a server-sent-event that is sent from an engine to a task.RespCh.
> Define pipeReadWriteCloser

- README.md
- engine/cmd/run.go
- engine/internal/processor/processor.go
- engine/internal/processor/processor_test.go
- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
- server/internal/infprocessor/pipe.go
- server/internal/server/ws_server.go
With this change, a inference request is processed with the following flow:
1. Server receives a request.
2. Server forwards the request to the engine.
3. Engine processes the request by talking to Ollama.
4. Engine sends the response back to the server.
5. Server forwards the response back to the client.
The engine and the server communicates with bi-directional gRPC.
> Add the multi-cluster support

- server/internal/router/router.go
Currently server fails if the engine is not running (and vice verse). This causes both into crash-looping.
This change fixes the issue by making the server gracefully handle an RPC error from the engine.
> Remove the hard mutual dependency between server and engine

- deployments/engine/templates/deployment.yaml
- deployments/engine/templates/serviceaccount.yaml
- deployments/engine/values.yaml
This is required when a user needs to a service account to give a S3 bucket access.
> Be able to create/use a service account

- deployments/server/templates/service.yaml
- deployments/server/values.yaml
This can be set to Loadbalancer or NodePort when the service is externally reachable.
> Be able to configure the type of worker grpc service

- deployments/engine/templates/configmap.yaml
- deployments/engine/templates/deployment.yaml
- deployments/engine/values.yaml
- engine/cmd/run.go
- engine/internal/config/config.go
Also consolidate Ollama config in a separate struct to help vLLM migration.
Having a longer keep-alive would help for now to avoid extra memory load time when the same model is used again and again.
> Increase Ollama keep alive to keep models in GPU memory for a longer period

- common/pkg/sse/scanner.go
- common/pkg/sse/scanner_test.go
Fix a bug where the split logic doesn't handle a case where atEOF is true but the data contains a double-new-lines.
> Make SSE splitting logic more robust

- build/engine/Dockerfile
Currently the image for ollama doesn't have inference-manager-engine.
> Fix Dockerfile

- engine/internal/ollama/manager.go
Use the string match to support the quantized model (= a model name with the "-q4" suffix).
> Fix deepseek-coder support in Ollama model file

- engine/internal/modelsyncer/syncer.go
- engine/internal/modelsyncer/syncer_test.go
As we start processing inference requests in parallel, the syncer receives multiple pull requests simultaneously.
This commit adds a synchronization on pull.
> Handle concurrent pull requests

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
- server/internal/router/router.go
- server/internal/router/router_test.go
When there is more than one engine that has a target model, pick up the least loaded one.
> Schedule a task to an engine that has the least number of running tasks

- engine/internal/ollama/manager.go
We need to have a different template for deepseek coder.
We need to see what's the best way to handle this as OpenAI API doesn't support the template change. A quick change is to just update the template.
> Update the template for deepseek coder to work with continue.dev

- deployments/server/values.yaml
250 millicores seems too small as "ollama list" is getting slow.
Set the request to 1 core and remove the limit. This is mostly Ok as the GPU node is dedicated to engine.
> Tweak the CPU allocation of engine

- deployments/engine/templates/configmap.yaml
- deployments/engine/templates/deployment.yaml
- deployments/engine/values.yaml
- engine/cmd/run.go
- engine/internal/config/config.go
- engine/internal/health/health.go
- engine/internal/manager/manager.go
- engine/internal/ollama/manager.go
- engine/internal/processor/processor.go
- engine/internal/vllm/manager.go
It can easily take more than several minutes to download & load large models. It is better to avoid a pod crash when the server is unreachable for a short period of time.
> Do not crash when inference-manager-server is unavailable

- deployments/engine/values.yaml
This can be longer. Given that loading a large model like llama3.1 70B is slow, we would like to avoid end users from hitting the model loading as much as possible.
> Increase the default keep alive to 96 hours

- engine/internal/ollama/manager.go
It seems Ollama always uses the default value (= 4098).
https://github.com/ollama/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values
> Set the context size of llama3.1 and deepseek coder

- engine/cmd/run.go
- engine/internal/manager/manager.go
- engine/internal/modelsyncer/syncer.go
- engine/internal/modelsyncer/syncer_test.go
- engine/internal/ollama/manager.go
- engine/internal/vllm/manager.go
This is neccessary when we make changes to model templates (e.g., context length).
> Update model templtes when cached models are found

- engine/internal/ollama/manager.go
The publicly announced max context length is 128K, but we limit the context length to 64K here to make this work smoothly in g5.48xlarge.
> Reduce the context size of llama3.1 to 64K

- deployments/engine/templates/configmap.yaml
- deployments/engine/values.yaml
- engine/internal/config/config.go
Ollama currently doesn't handle multiple H100s (https://github.com/ollama/ollama/issues/5494).
This is a workaround described in the above ticket.
> Add a force-spreading option

- deployments/engine/templates/configmap.yaml
- deployments/engine/values.yaml
ollama.numParallel is something end users change, and I wanted to avoid exposing the internal implementation details.
> Add maxConcurrentRequests instead of ollama.numParallel

- engine/internal/ollama/env.go
This was accidentally removed with
https://github.com/llm-operator/inference-manager/pull/206
> Add back ollama keep alive logic

- engine/internal/ollama/manager.go
Do not buffer as some of the useful debug info from "ollama serve" is written to stderr.
> Write ollama err to stderr

- engine/internal/processor/processor.go
Instead of just logging an error message, make the engine report the error to the server so that the server can send that to a client.
> Send an error to a server when an engine fails to talk to an LLM engine

- engine/internal/processor/processor.go
- engine/internal/runtime/manager.go
We got a timeout error or a connection-refused error when a request is sent immediately after a statefulset becomes reachable.
This can be because it takes some time until an endpoint is created and kube-proxy updates ipfilter.
Checking the actual reachability will be needed.
> Check if the service is reachable before making it ready

- deployments/engine/templates/configmap.yaml
- deployments/engine/values.yaml
- engine/internal/config/config.go
- engine/internal/ollama/env.go
- engine/internal/runtime/ollama_client.go
Ollama creaets a payload in a temporary directory by default, and a new temporary directory is created whenever Ollama restarts. This is a problem when a persistent volume is mounted. To avoid this, we set the directory to a fixed path.
> Use a fix dir for ollama payload

- engine/cmd/alpha.go
- engine/cmd/pull.go
- engine/cmd/run.go
- engine/internal/config/config.go
- engine/internal/config/config_test.go
- engine/internal/runtime/client.go
Model IDs we use in model-manager-loader contains "/". Allow end users to have the same format in inference-manager-engine.
> Be able to use consistent format for model IDs

- engine/cmd/pull.go
- engine/internal/runtime/client.go
If true, all pods pull a specified model. This is needed when pods don't have a shared volume.
> Add --force-pull

- server/internal/server/completions.go
- server/internal/server/legacy_completions.go
Add a missing 'return' after calling http.Error().
> Fix a bug from refactoring in (legacy_)completions.go

- engine/cmd/alpha.go
- engine/internal/runtime/client.go
- engine/internal/runtime/ollama_client.go
- engine/internal/runtime/vllm_client.go
- engine/internal/runtime/vllm_client_test.go
- engine/internal/vllm/manager.go
- engine/internal/vllm/models.go
We used to infer a model format from a model ID, but it didn't work when a model supports multiple formats.
Change the code to retrieve the format from model-manager-server when creating a stratefulset.
> Retrieve a model format when creating a statefulset

- engine/internal/vllm/manager.go
- engine/internal/vllm/manager_test.go
We have the same mechanism in Ollama, but vLLM didn't have.
Create a file that indicates the completion of download, and do not download again if the file exists.
> Do not download the model multiple times (for vLLM)

- deployments/engine/templates/servicemonitor.yaml
- deployments/engine/values.yaml
vLLM exports Prometheus metrics (https://github.com/vllm-project/vllm/blob/main/examples/production_monitoring/README.md), which we can set up a ServiceMonitor to collect metrics.
> Add an optional servicemonitor for cllecting runtime metrics

- deployments/engine/values.yaml
We no longer need to allocate GPU as model pods have GPUs instead.
> Do not allocate GPU to the engine pod

- engine/cmd/run.go
- engine/internal/runtime/vllm_client.go
This doesn't work when the function is called from processor.P as the context already has a worker authorization (and adding it again breaks gRPC).
Instead of appending in modelFilePath(), do this in preload().
> Do not append worker authorization in modelFilePath()

- .github/workflows/ci-post-merge.yml
- Makefile
- build/engine/Dockerfile
Still build an image with Ollama base so that we can fall back to the previous behavior, but change the default image to not include Ollama anymore.
> Use distroless for a base image for inference-manager-engine

- engine/internal/modeldownloader/modeldownloader.go
- engine/internal/modeldownloader/modeldownloader_test.go
- engine/internal/runtime/vllm_client_test.go
- engine/internal/vllm/manager.go
- engine/internal/vllm/models.go
To share the code with the Ollama runtime case.
> Factor out the model download logic to a separate package

- engine/cmd/run.go
- engine/internal/runtime/manager.go
Manager calls Register() and Unregister(). We shouldn't call them when autoscaling is disabled.
> Make Register & Unregister no-op when autoscaling is disabled

- engine/internal/runtime/ollama_client.go
Model names were still using hard-coded ones.
> Fix an init container command for creating Ollama modelfile

- server/internal/server/server.go
Define the interface when it is actually used.
> Move the definition of MetricsMonitoring to the server package

- engine/internal/runtime/vllm_client.go
Remove the template for sentence-transformers-all-MiniLM-L6-v2 from vLLM as it doesn't work (no support of "bert" architecture).
> Add a template for intfloat/e5-mistral-7b-instruct in vLLM

- engine/internal/config/config.go
Handle a case where the runtime name is configured in the "model" instead of "runtime".
> Fix the runtime image config validation

- deployments/server/templates/ingress.yaml
- deployments/server/values.yaml
This is never used as inference-manager-engine talks to inference-manager-server without an ingress controller.
> Do not create an ingress for the worker service

- engine/internal/runtime/preloader.go
Do not use a non-blocking select.
> Fix the sleep login in preloader

- server/internal/server/completions.go
This is a temporary solution as continue.ev does not provide a way to the stream options.
> Include usages in streaming by default

- .github/workflows/ci-post-merge.yml
- Makefile
- build/triton-proxy/Dockerfile
- triton-proxy/cmd/main.go
- triton-proxy/cmd/root.go
- triton-proxy/cmd/run.go
- triton-proxy/internal/config/config.go
- triton-proxy/internal/server/completions.go
- triton-proxy/internal/server/server.go
- triton-proxy/internal/server/triton.go
- triton-proxy/internal/server/triton_test.go
This is a simple HTTP server that receives OpenAI-compatible API requests and forwards to Triton Inference Server.
We don't need this once Triton Inference Server supports OpenAI compatible API, but meanwhile we can run this together with the Triton Inference Server container in the same pod.
> Add triton-proxy

- engine/internal/runtime/triton_client.go
This is a hack to make things work. We need to store the path in Model Manager..
> Append repo/llama3 to the triton model registry path

- engine/internal/modeldownloader/common/common.go
- engine/internal/modeldownloader/common/common_test.go
Triton model files contain "repo/llama3/ensemble/1/.tmp", which we cannot exclude. It seems the content of .tmp does not matter, but we need the directory.
> Do not skip a hidden file when downloading model files

- engine/internal/modeldownloader/modeldownloader.go
Previously, we only update one GGUF file for a fine-tuning job, and the file key is the same as the model path.
As we changed fine-tuning jobs to upload multiple files, we need a corresponding change here.
> Update the model file for Ollama fine-tuning

- server/internal/router/router.go
This can be confusing for single-tenant use cases.
> Do not mention a tenant in an error message

- engine/internal/runtime/vllm_client.go
vLLM currently supports only the 'bitsandbytes' load format for BitsAndBytes quantization.
> fix(runtime): set --load-format to "bitsandbytes" for a bnb-quantized models

- engine/internal/runtime/client.go
We need to append 'params.volumes' to 'volumes'.
> fix(runtime): Add back missing volumes for /dev/shm

- deployments/engine/templates/configmap.yaml
- deployments/engine/values.yaml
- engine/internal/config/config.go
- engine/internal/config/model_config.go
- engine/internal/runtime/vllm_client.go
For some cases, we would like to set flags like --gpu-utilization or --enforce-eager.
> feat(runtime): Be able to specify extra flags for vLLM

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
We didn't acquire a lock when p.engines is accessed. This commit fixes the bug by moving the logic to findLeastLoadedEngine.
> fix(server): Correctly acquire a lock in scheduleTask

- deployments/server/templates/configmap.yaml
- deployments/server/values.yaml
- server/cmd/run.go
- server/internal/config/config.go
- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
We temporarily disabled this since there is an old version of inference-manager-engine that doesn't set the 'ready' field.
Add back the code, but also add a flag to disable this.
> fix(server): re-enable the engine readiness check

- server/cmd/run.go
- server/internal/infprocessor/engine_tracker.go
- server/internal/infprocessor/engine_tracker_test.go
- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
- server/internal/server/ws_server.go
The forwarding logic has not yet been implemented, but use DB to route requests.
> feat(server): use engine status in DB to route requests

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/pipe.go
Move the logic from ProcessTaskResult to sendTask.
This is needed as an upcoming change requires a function that just forwards task results to a remote server without any additional processing.
> refactor(server): refactor the logic for processing tasks results

- engine/internal/processor/processor.go
- engine/internal/processor/processor_test.go
- engine/internal/runtime/manager.go
- engine/internal/runtime/manager_test.go
The 'ctx' arg is unused. This is also misleading since the function is called after the context is canceled.
> chore(engine): remove the 'ctx' arg from sendEngineStatus

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
- server/internal/server/ws_server.go
The function is used to process a task forwarded from other server instance.
Make another refactoring and clean up the logic for updating `inProgressTasksByID`. It is now consolidated in `enqueueAndProcessTask`.
> feat(server): add SendAndProcessTask to infprocessor.P

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
- server/internal/server/ws_server.go
Currently every engine is a locally connected one, but this is needed when we have remotely-connected engines.
> feat(server): make the task scheduler prefer a local engine

- server/internal/infprocessor/infprocessor.go
- server/internal/infprocessor/infprocessor_test.go
We need a function that returns only local engines. Including remote engines cause a loop in a status reporting.
> chore(server): update Engines() to LocalEngines()

- common/pkg/test/log.go
Call stdr.SetVerbosity(8) from init() to avoid a test failure like below:
https://github.com/llmariner/inference-manager/actions/runs/11504696862/job/32024755965
> fix(common): fix a race condition in NewTestLogger

- engine/internal/runtime/vllm_client.go
Increase the RPC timeout (default: 10 seconds) as we hit https://github.com/vllm-project/vllm/discussions/9418 when running the Nvidia Llama3.1 Nemotron 70B with a larger context size.
> feat(engine): set VLLM_RPC_TIMEOUT to a larger value

- deployments/engine/templates/configmap.yaml
- engine/internal/config/config.go
- engine/internal/runtime/client.go
One use case is to pass an annotation for kube2iam, but this should be generally useful.
> feat(engine): propagate pod annotations to runtime pods

- Makefile
To avoid failure in applying helmfile after updating llmariner repostiory.
> ci(chart): cleanup LLMariner Chart.lock for test

- engine/internal/processor/processor.go
Run into error when sending request to vllm:
` 'msg': 'Extra inputs are not permitted', 'input': 'what is k8s?'}, {'type': 'extra_forbidden', 'loc': ('body', 'messages', 0, 'typed-dict', 'legacy_content'), 
`
> fix(engine): unset legacyContent

- deployments/engine/templates/configmap.yaml
To prevent pretty-printed YAML in the ConfigMap from breaking.
> refactor(chart): wrap optional values with `with`

- engine/internal/runtime/vllm_client.go
- engine/internal/runtime/vllm_client_test.go
Inferentia nodes have the "aws.amazon.com/neuroncore" resource. When the resource is allocated to a vLLM pod, --tensor-paralle-size is set to the same value.
> feat(engine): set --tensor-paralle-size for Inferentia nodes

- engine/internal/modeldownloader/huggingface/download.go
Not all models have special_tokens_map.json.
https://huggingface.co/Qwen/Qwen2-7B/tree/main is one example.
> fix(engine): make special_tokens_map.json optional

- server/internal/infprocessor/infprocessor_test.go
https://github.com/llmariner/inference-manager/actions/runs/12757123737/job/35557380598?pr=540
Finish the test after the gorountime completes. Otherwise the logging can cause a data race error.
> fix(server): fix a data race in TestSendAndProcessTask

- engine/internal/runtime/manager.go
- engine/internal/runtime/manager_test.go
Swap the position of 'added' and 'ready' for the following reasons:
- The caller first checks 'added'.
- 'ready' is set to a meaningful value only when 'added' is true.
> chore(engine): add the position of return bool values of addRunTime

- server/internal/server/completions.go
- server/internal/server/embeddings.go
- server/internal/server/legacy_completions.go
Passing headers like Origin makes Ollama return 403. We can set env var OLLAMA_ORIGINS to "*" in Ollama containers (c.f., https://github.com/ollama/ollama/issues/4115) to work around 403, but it's better to drop the headers.
> fix(server): drop unneeded headers

- deployments/engine/templates/configmap.yaml
With https://github.com/llmariner/inference-manager/pull/583, we get the following in the configmap:
```yaml
model:
default:
runtimeName: ollama
resources:
volume: {}
```
Since volume is set, we get the following error:
```bash
Error: model: default: volume: accessMode must be set
```
To make the 'volume' field optional, set the invidiual fields resources separately.
> fix: fix the resources field in the configmap

- server/internal/infprocessor/infprocessor.go
The LocalEngines function is used when an inference-manager-server instance reports its connected engines to other instances.
Setting the clusterId here is needed to properly show clusters in the status endpoint.
> fix: set ClusterId from LocalEngines

- server/internal/infprocessor/infprocessor.go
- server/internal/server/status.go
infprocessor.P keeps only ready engines. So the Ready field should be alwyas true.
> fix: set EngineStatus.Ready to true

- build/engine/Dockerfile
The nonroot image does not have permission to write ebs volume. We can set the securityContext and change group, but it leads to permission mismatch to vllm image.
> fix: use normal distroless image as a base image for the engine

- engine/internal/runtime/vllm_client.go
- engine/internal/runtime/vllm_client_test.go
When LoRA is used, set --served-model-name to the base model name ID, not to the fine-tuned model ID.  vLLM serves both the base model and the fined-tune model, and --served-model-name is used to specify the base model name.
See https://docs.vllm.ai/en/v0.5.5/models/lora.html#serving-lora-adapters.
> fix: fix LoRA serviing in vLLM

- engine/cmd/pull.go
- engine/cmd/run.go
- engine/internal/runtime/manager.go
- engine/internal/runtime/ollama_client.go
- engine/internal/runtime/ollama_manager.go
- engine/internal/runtime/preloader.go
Sample configuration:
```diff
--- a/hack/values.yaml
+++ b/hack/values.yaml
@@ -29,6 +29,8 @@ inference-manager-engine:
repository: llmariner/inference-manager-engine
pullPolicy: Never
replicaCount: 1
+  ollama:
+    dynamicModelLoading: true
model:
default:
runtimeName: ollama
@@ -47,4 +49,5 @@ inference-manager-engine:
model-manager-loader:
runOnce: true
+  downloader:
+    kind: ollama
baseModels:
-  - google/gemma-2b-it-q4_0
+  - gemma2:2b
+  - deepseek-r1:1.5b
```
> feat(engine): add ollama manager for multiple model loading

- engine/internal/runtime/ollama_client.go
Need to remove "ft:" from the model name when running "ollama create".
> fix: support fine-tuning models in Ollama dynamic mode

- server/internal/rate/limiter.go
- server/internal/server/completions.go
- server/internal/server/embeddings.go
- server/internal/server/legacy_completions.go
The function only works for gRPC endpoint, and
it doesn't work for HTTP handlers.
> fix: do not use ExtractUserInfoFromContext

- engine/cmd/run.go
- engine/internal/processor/processor.go
- engine/internal/processor/processor_test.go
This will recreate a new TCP connection and avoid sending traffic to unready pods.
> fix: recreate a gRPC client whenever run() is called

- server/internal/taskexchanger/task_receiver.go
Recreate a map so that a tenant is removed from the map when there is no engine.
> fix: correctly refresh the engine status cache

- engine/internal/runtime/updater.go
Avoid the following error:
Error: controller with name statefulset already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric
> fix: avoid duplicated name for the updater controller

- deployments/server/templates/ingress.yaml
The vLLM endpoint doesn't have "v1", but we keep v1 for consistency.
> feat: add ingress for /v1/tokenize
